version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: "Say hi!"
          command: echo "Hello, CI"
      - run:
          name: "List repo dir"
          command: ls -R
      - run:
          name: "Read text.txt"
          command: cat ./text.txt

      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
workflows:
  version: 2
  release:
    jobs:
      - build:
          filters:
            tags:
              only: /^(.*?)-release$/
            branches:
              ignore: /.*/
