version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: "Say hi!"
          command: echo "Hello, CI"
      - run:
          name: "List repo dir"
          command: ls -R
workflows:
  version: 2
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^(.*?)-release$/
